#====================================================================#
[[icon.conds]]
if    = "hidden & dir"
text  = ""

[[icon.conds]]
if    = "dir"
text  = ""

[[icon.conds]]
if    = "!(dir | link)"
text  = ""

[[icon.conds]]
if    = "link"
text  = ""
#====================================================================#

#====================================================================#
[[icon.dirs]]
name  = "Downloads"
text  = ""

[[icon.dirs]]
name  = "Documents"
text  = ""

[[icon.dirs]]
name  = "Pictures"
text  = ""

[[icon.dirs]]
name  = "Videos"
text  = ""
#====================================================================#

