#=========================================================#
[manager]
show_hidden     = true
show_symlink    = true
#=========================================================#

#=========================================================#
[preview]
wrap            = "no"
tab_size        = 4
max_width       = 650
max_height      = 950
#=========================================================#

