#===============================================================#
gui:
  showFileIcons: true
  nerdFontsVersion: 3
  showCommandLog: false
  sidePanelWidth: 0.35
  showPanelJumps: false
  showBottomLine: false
#===============================================================#

#===============================================================#
git:
  paging:
    colorArg: always
    pager: delta --paging=never --hunk-header-style=omit
#===============================================================#

#===============================================================#
os:
  editPreset: 'nvim'
#===============================================================#

#===============================================================#
update:
  method: never
#===============================================================#

